// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railcar.Data;

#nullable disable

namespace Railcar.Data.Migrations
{
    [DbContext(typeof(RailcarDbContext))]
    [Migration("20260208053137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Railcar.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Railcar.Data.Entities.EquipmentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EventLocalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventUtcTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TripId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("EventCode");

                    b.HasIndex("TripId");

                    b.ToTable("EquipmentEvents");
                });

            modelBuilder.Entity("Railcar.Data.Entities.EventCodeDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Code");

                    b.ToTable("EventCodeDefinitions");
                });

            modelBuilder.Entity("Railcar.Data.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalTripHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Railcar.Data.Entities.EquipmentEvent", b =>
                {
                    b.HasOne("Railcar.Data.Entities.City", "City")
                        .WithMany("EquipmentEvents")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railcar.Data.Entities.EventCodeDefinition", "EventCodeDefinition")
                        .WithMany("EquipmentEvents")
                        .HasForeignKey("EventCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railcar.Data.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId");

                    b.Navigation("City");

                    b.Navigation("EventCodeDefinition");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Railcar.Data.Entities.Trip", b =>
                {
                    b.HasOne("Railcar.Data.Entities.City", "DestinationCity")
                        .WithMany("DestinationTrips")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Railcar.Data.Entities.City", "OriginCity")
                        .WithMany("OriginTrips")
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("Railcar.Data.Entities.City", b =>
                {
                    b.Navigation("DestinationTrips");

                    b.Navigation("EquipmentEvents");

                    b.Navigation("OriginTrips");
                });

            modelBuilder.Entity("Railcar.Data.Entities.EventCodeDefinition", b =>
                {
                    b.Navigation("EquipmentEvents");
                });

            modelBuilder.Entity("Railcar.Data.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
